### PR TITLE
Fix compilation for other target architectures

### LINKED ISSUE #52: Help finding solution to mips compilation failure
https://github.com/tessel/t2-cli/issues/645#issuecomment-207675894

Is there anyway to work around this? Even if it's a JS only "fallback"? It's been a long day, so this might not even make sense

### PR DESCRIPTION
**Pull request by anandsuresh**
Long outstanding compilation issue fixes for different target architectures (mainly those that have no support for SSE 4.2 extensions).

Fixes #52

### CODE REVIEW

**Comment by anandsuresh** [comment]
@rwaldron Can you please pull this branch and check if it fixes your problems?

**Comment by rwaldron** [comment]
I will give this a try today—Thanks!

**Comment by rwaldron** [comment]
I'll omit most of the junk stuff, here's the important part: 

```
make: Entering directory `/work/binary-module/package/build'
  CXX(target) Debug/obj.target/sse4_crc32/src/crc32c.o
/tmp/cc7IyA0N.s: Assembler messages:
/tmp/cc7IyA0N.s:4600: Error: unrecognized opcode `pushl %ebx'
/tmp/cc7IyA0N.s:4601: Error: unrecognized opcode `cpuid '
/tmp/cc7IyA0N.s:4602: Error: unrecognized opcode `movl %ebx,$7'
/tmp/cc7IyA0N.s:4603: Error: unrecognized opcode `popl %ebx'
make: *** [Debug/obj.target/sse4_crc32/src/crc32c.o] Error 1
make: Leaving directory `/work/binary-module/package/build'
```

**Comment by anandsuresh** [comment]
Oh man! Forgot I had some assembly code in that file there. Might need to add some MIPS specific stuff in there to bypass that section.

**Comment by rwaldron** [comment]
Sorry for that 22 hour delay in checking this :| we had guests and then I was driving all last night. I will be more on-top of this :)

**Comment by anandsuresh** [comment]
No worries mate. I'm gonna be a bit busy this week, but will try and get to this during some down-time at the end of the day.

The key idea now is to override the `cpuid` function to do the right thing for the MIPS platform, and/or setup the `reg` structure in a manner that would cause the `isSSE42Available()` to return false. That should solve the issues you are facing and make this module more robust on non-Intel platforms.

**Comment by rwaldron** [comment]
That's awesome—thank you for the extra details and for working to resolve this :)

**Comment by anandsuresh** [comment]
@rwaldron I updated this branch (sorry, I force-pushed to the same commit) fixes that should hopefully solve your problem. Give it a go and let me know if it works.

**Comment by rwaldron** [comment]
I'll put this on my to-do for today and report back as soon as I can, thanks again!

**Comment by rwaldron** [comment]
I might be the worst at sticking to a daily to-do list ;)

The results are in: the latest version of this PR compiles successfully!

**Comment by anandsuresh** [comment]
@rwaldron Thats awesome. Can you also please run the tests using `npm test` to see if the results are correct for the platform? As per the updated code, you should be using the software-fallback using the table-lookup. Just want to confirm that the results returned are correct.

**Comment by rwaldron** [comment]
Not sure I can do it exactly that way. For Tessel 2 dev, the end developer writes the whole program on their local machine, npm installing as needed, then deploys to the board with our CLI tool. The CLI tool does a detection and swapping algo to replace compiled addons with their appropriate mips target precompiled modules. So what I'll do is move the tests to a program and deploy that, should be good to go, but won't be via `npm test`

**Comment by rwaldron** [comment]
I "ported" the tests to a stand alone script: 

```js
var Sse4Crc32 = require("sse4_crc32");

var testCases = {
  'string': {
    input : 'SSE4-CRC32: A hardware accelerated CRC32 implementation for node.js',
    output: 3039989317
  },
  'buffer': {
    input : new Buffer('SSE4-CRC32: A hardware accelerated CRC32 implementation for node.js'),
    output: 3039989317
  }
};

Object.keys(testCases).forEach(function(inputType) {
  console.log(Sse4Crc32.calculate(testCases[inputType].input) === testCases[inputType].output ? 'PASS' : 'FAIL', inputType);
});


console.log(typeof Sse4Crc32.CRC32 === 'function' ? 'PASS' : 'FAIL');

try {
  new Sse4Crc32.CRC32();
  console.log('PASS');
} catch (e) {
  console.log('FAIL');
}

var input = null;
var initialCrc = 10;

console.log(new Sse4Crc32.CRC32(input).crc32c === 0 ? 'PASS' : 'FAIL');
console.log(new Sse4Crc32.CRC32(input, initialCrc).crc32c === initialCrc ? 'PASS' : 'FAIL');

input = 'input';

console.log(new Sse4Crc32.CRC32(input).crc() === 3633258352 ? 'PASS' : 'FAIL');

var crc = new Sse4Crc32.CRC32(input);

console.log(crc.crc() === 3633258352 ? 'PASS' : 'FAIL');

crc.update(' progressive');
console.log(crc.crc() === 1233760415 ? 'PASS' : 'FAIL');
```

And deployed it to the Tessel 2: 

```
$ t2 run test.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (40.448 kB)...
INFO Deployed.
INFO Running test.js...
PASS string
PASS buffer
PASS
PASS
PASS
PASS
PASS
PASS
PASS
```


I'd say that's a successful run :)

**Comment by anandsuresh** [comment]
Perfect. I have a few more minor changes; nothing that should affect your build, just some clean up and changes to better support non-Intel platforms. Thanks for the assistance. Non-Intel platform support is something I've been thinking about for a while, but never got around to working on.

Once the CI stuff clears up, I'll merge and release a new major version of the module (v5.0.0). That should hopefully fix the problems you've been facing.

**Comment by anandsuresh** [comment]
@rwaldron  Published sse4_crc32 v5.0.0.

**Comment by rwaldron** [comment]
Very cool—thank you for your excellent maintainership :)

**Comment by johnnyman727** [comment]
:clap:

**Pull request merged**
